export const playerPause = require('../../assets/icons/player-pause.png')
export const playerPlay = require('../../assets/icons/player-play.png')
export const playerRestart = require('../../assets/icons/player-restart.png')
export const disableFullscreen = require('../../assets/icons/disable-fullscreen.png')
export const enableFullscreen = require('../../assets/icons/enable-fullscreen.png')
